DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article`
(
   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `title` VARCHAR(50) NOT NULL,
   `author` VARCHAR(20) NOT NULL,
   `timestamp` int(11)  UNSIGNED NOT NULL,
   `content` MEDIUMTEXT NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 

DROP TABLE IF EXISTS `comment`;
CREATE TABLE IF NOT EXISTS `comment`
(
   `cid` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
   `id` BIGINT UNSIGNED NOT NULL,
   `fromIP` VARCHAR(20) NOT NULL,
   `timestamp` int(11)  UNSIGNED NOT NULL,
   `content` MEDIUMTEXT NOT NULL,
   PRIMARY KEY (`Cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
